# Generated by Django 5.1.1 on 2024-09-27 10:54

import cars.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=128, validators=[cars.validators.TitleValidator()], verbose_name='Марка автомобиля')),
                ('model', models.CharField(max_length=128, validators=[cars.validators.TextValidator()], verbose_name='Модель автомобиля')),
                ('year', models.PositiveIntegerField(validators=[cars.validators.CarYearValidator()], verbose_name='Год выпуска')),
                ('description', models.TextField(validators=[cars.validators.TextValidator()], verbose_name='Описание автомобиля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи об автомобиле.')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего обновления записи.')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(validators=[cars.validators.TextValidator()], verbose_name='Cодержание комментария.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания комментария об автомобиле.')),
            ],
        ),
    ]
