# Generated by Django 5.1.1 on 2024-09-28 11:33

import cars.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True, validators=[cars.validators.CarYearValidator()], verbose_name='Год выпуска'),
        ),
    ]
